feat: adding Dockerfile.multiarch
hivesolutions/headless pull request #17
Opened 2024-02-29 18:08 UTC by hugo-gomes

https://github.com/hivesolutions/headless/issues/13#issuecomment-1969911233

2024-02-29 18:39 UTC, hugo-gomes commented
@joamag https://hub.docker.com/r/hivesolutions/headless/tags?page=1&name=headless-chromium

2024-03-01 09:05 UTC, joamag requested changes

2024-03-01 09:05 UTC, joamag commented on .github/workflows/dockerx.yml
> +'on':
no need for the '

2024-03-01 09:05 UTC, joamag commented on .github/workflows/dockerx.yml
> +    runs-on: self-hosted
I think we can run these directly on github without s6.hive

This is an open source project

2024-03-01 16:22 UTC, hugo-gomes commented
@joamag https://hub.docker.com/r/hivesolutions/headless/tags?page=1&name=chromium

2024-03-01 17:59 UTC, joamag approved these changes

2024-03-01 17:59 UTC, merged